/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author ISABELLA CARMONA C
 */
public class FrmEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCbTipoID = new javax.swing.JComboBox<>();
        jTxNumeroID = new javax.swing.JTextField();
        jTxNombres = new javax.swing.JTextField();
        jTxApellidos = new javax.swing.JTextField();
        jTxTelefono = new javax.swing.JTextField();
        jTxDireccion = new javax.swing.JTextField();
        jCbRH = new javax.swing.JComboBox<>();
        jCbARL = new javax.swing.JComboBox<>();
        jBtAgregar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTxSalario = new javax.swing.JTextField();
        jBtSalir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jDtFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jTxEPS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxCargo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jBtAgregarArchivos = new javax.swing.JButton();
        jLbDirecArchivo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("EMPLEADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 0, 170, 34));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Identificación: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombres: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 109, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellidos: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 109, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Dirección: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 241, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha de Nacimiento: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 164, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Teléfono: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 167, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("RH: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 241, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("EPS:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 385, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ARL:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 318, -1, -1));

        jCbTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECCIONE TIPO DE DOCUMENTO-", "Cédula de Ciudadanía", "Cédula de Extranjería", "PEP" }));
        getContentPane().add(jCbTipoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 62, 242, -1));
        getContentPane().add(jTxNumeroID, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 63, 242, -1));
        getContentPane().add(jTxNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 106, 242, -1));
        getContentPane().add(jTxApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 106, 242, -1));
        getContentPane().add(jTxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 164, 242, -1));
        getContentPane().add(jTxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 238, 242, -1));

        jCbRH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECCIONE RH-", "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));
        getContentPane().add(jCbRH, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 237, 242, -1));

        jCbARL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SURA" }));
        getContentPane().add(jCbARL, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 314, 242, -1));

        jBtAgregar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBtAgregar.setText("Agregar");
        getContentPane().add(jBtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 487, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Salario Base:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 385, -1, -1));
        getContentPane().add(jTxSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 382, 241, -1));

        jBtSalir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBtSalir.setText("Salir");
        getContentPane().add(jBtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 487, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Número:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 66, -1, -1));
        getContentPane().add(jDtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 164, 242, -1));
        getContentPane().add(jTxEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 382, 242, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cargo:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 318, -1, -1));
        getContentPane().add(jTxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 315, 242, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Hoja de vida:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jBtAgregarArchivos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jBtAgregarArchivos.setText("Añadir Archivos");
        getContentPane().add(jBtAgregarArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jLbDirecArchivo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLbDirecArchivo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLbDirecArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 441, 351, 32));

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*Solo se permiten archivos PDF ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 191, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtAgregar;
    public javax.swing.JButton jBtAgregarArchivos;
    public javax.swing.JButton jBtSalir;
    public javax.swing.JComboBox<String> jCbARL;
    public javax.swing.JComboBox<String> jCbRH;
    public javax.swing.JComboBox<String> jCbTipoID;
    public com.toedter.calendar.JDateChooser jDtFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLbDirecArchivo;
    public javax.swing.JTextField jTxApellidos;
    public javax.swing.JTextField jTxCargo;
    public javax.swing.JTextField jTxDireccion;
    public javax.swing.JTextField jTxEPS;
    public javax.swing.JTextField jTxNombres;
    public javax.swing.JTextField jTxNumeroID;
    public javax.swing.JTextField jTxSalario;
    public javax.swing.JTextField jTxTelefono;
    // End of variables declaration//GEN-END:variables
}
