/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ISABELLA CARMONA C
 */
public class FrmNomina extends javax.swing.JFrame {

    /**
     * Creates new form FrmNomina
     */
    public FrmNomina() {
        initComponents();

        jTxEmpleado.setEnabled(false);
        jTxDocumento.setEnabled(false);
        jTxCargo.setEnabled(false);
        jTxSalarioBase.setEnabled(false);
        jTxAuxTransp.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxCargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxSalarioBase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxPagoQuincena = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxAuxTransp = new javax.swing.JTextField();
        jLbPagoPeriodo = new javax.swing.JLabel();
        jTxPagoAuxTransp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxBonificacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxTotalDevengado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxNetoPagar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxDocumento = new javax.swing.JTextField();
        jTxFechaCorte = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTxPrestamo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTxTotalDeducciones = new javax.swing.JTextField();
        jBtGuardar = new javax.swing.JButton();
        jBtEditar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTxDiasTrabajados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Nomina.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Javanese Text", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Restaurante Delicias de Calasanz");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 15, 443, 36));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("EMPLEADO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTxEmpleado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PENSIÓN (4%)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        jTxCargo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 171, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Auxilio Transporte:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jTxSalarioBase.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxSalarioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 150, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Días trabajados:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jTxPagoQuincena.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxPagoQuincena, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 150, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("_______________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 260, 20));

        jTxAuxTransp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxAuxTransp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 150, -1));

        jLbPagoPeriodo.setBackground(new java.awt.Color(0, 0, 0));
        jLbPagoPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbPagoPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        jLbPagoPeriodo.setText("Pago periodo (15 dias):");
        jPanel1.add(jLbPagoPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTxPagoAuxTransp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxPagoAuxTransp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 150, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Pago periodo Aux (15 dias):");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jTxBonificacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxBonificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 150, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Bonificación:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jTxTotalDevengado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxTotalDevengado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 150, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Total Devengado:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jTxNetoPagar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxNetoPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 150, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Neto Pagar (total deducciones):");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("FIRMA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CARGO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Periodo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jTxDocumento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 210, -1));

        jTxFechaCorte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxFechaCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 180, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("DOCUMENTO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Préstamo:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("SALUD (4%)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("DEDUCCIONES");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("TOTAL DEDUCCIONES");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jTxPrestamo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 170, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Otras deducciones:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        jTxTotalDeducciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxTotalDeducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 170, -1));

        jBtGuardar.setText("Guardar");
        jPanel1.add(jBtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, -1, -1));

        jBtEditar.setText("Editar");
        jPanel1.add(jBtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 70, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("SALARIO BASE:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jTxDiasTrabajados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTxDiasTrabajados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 150, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtEditar;
    public javax.swing.JButton jBtGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbPagoPeriodo;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxAuxTransp;
    public javax.swing.JTextField jTxBonificacion;
    public javax.swing.JTextField jTxCargo;
    public javax.swing.JTextField jTxDiasTrabajados;
    public javax.swing.JTextField jTxDocumento;
    public javax.swing.JTextField jTxEmpleado;
    public javax.swing.JTextField jTxFechaCorte;
    public javax.swing.JTextField jTxNetoPagar;
    public javax.swing.JTextField jTxPagoAuxTransp;
    public javax.swing.JTextField jTxPagoQuincena;
    public javax.swing.JTextField jTxPrestamo;
    public javax.swing.JTextField jTxSalarioBase;
    public javax.swing.JTextField jTxTotalDeducciones;
    public javax.swing.JTextField jTxTotalDevengado;
    // End of variables declaration//GEN-END:variables
}
