/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorEditarPerfil;
import controlador.ControladorEmpleado;
import controlador.ControladorLiquidacion;
import controlador.ControladorVerNomina;
import controlador.ControladorVerNovedades;
import controlador.ControladorVisualizarEmpl;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import modelo.Administrador;
import modelo.AdministradorDAO;
import modelo.AsistenciaDAO;
import modelo.Empleado;
import modelo.EmpleadoDAO;
import modelo.Novedades;
import modelo.NovedadesDAO;
import modelo.Salario;
import modelo.SalarioDAO;

/**
 *
 * @author SALA404-406
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cerrar();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMIGenerarNomina = new javax.swing.JMenuItem();
        jMILiquidarEmpleado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1266, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );

        jMenu2.setText("Empleados");

        jMenuItem1.setText("Turnos");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Ver Novedades");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Agregar Empleados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Mostrar Empleados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Nómina");

        jMIGenerarNomina.setText("Generar Nómina");
        jMIGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGenerarNominaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGenerarNomina);

        jMILiquidarEmpleado.setText("Liquidar Empleado");
        jMILiquidarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILiquidarEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(jMILiquidarEmpleado);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Calendario");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Perfil");

        jMenuItem6.setText("Editar Perfil");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("SALIR PROGRAMA");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmEmpleados frmEmpleados = new FrmEmpleados();
        Empleado empleado = new Empleado();
        EmpleadoDAO empleadod = new EmpleadoDAO();
        ControladorEmpleado control = new ControladorEmpleado(frmEmpleados, empleado, empleadod);
        jDesktopPane1.add(frmEmpleados); //Crea un objeto de tipo form y sobrepone un panel sobre otro

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = frmEmpleados.getSize();
        frmEmpleados.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmEmpleados.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmVisualizarEmpleados frmVisualizar = null;
        try {
            frmVisualizar = new FrmVisualizarEmpleados();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Empleado empleado = new Empleado();
        EmpleadoDAO empleadod = new EmpleadoDAO();
        ControladorVisualizarEmpl control = new ControladorVisualizarEmpl(frmVisualizar, empleado, empleadod);
        jDesktopPane1.add(frmVisualizar); //Crea un objeto de tipo form y sobrepone un panel sobre otro

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = frmVisualizar.getSize();
        frmVisualizar.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmVisualizar.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro de salir?", "Vuelva pronto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Administrador admin = new Administrador();
        AdministradorDAO admindao = new AdministradorDAO();

        FrmEditarPerfil form1 = new FrmEditarPerfil();

        ControladorEditarPerfil control1 = new ControladorEditarPerfil(form1, admin, admindao);
        try {
            admin = admindao.traerDatos();
        } catch (SQLException ex) {
            Logger.getLogger(ControladorEditarPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }

        form1.jTxNewUser.setText(admin.getUser());
        form1.jPFNewPassword.setText(admin.getPassword());
        form1.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        confirmarSalida();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmVerNovedades frm = null;
        try {
            frm = new FrmVerNovedades();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        Novedades novedad = new Novedades();
        NovedadesDAO novedaddao = new NovedadesDAO();
        try {
            ControladorVerNovedades control = new ControladorVerNovedades(frm, novedad, novedaddao);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(frm); //Crea un objeto de tipo form y sobrepone un panel sobre otro

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = frm.getSize();
        frm.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frm.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMIGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGenerarNominaActionPerformed

        Empleado empleado = new Empleado();
        EmpleadoDAO empleadod = new EmpleadoDAO();
        AsistenciaDAO asistdao = new AsistenciaDAO();
        Salario salario = new Salario();
        FrmVerNomina fnomina = new FrmVerNomina();
        ControladorVerNomina control = new ControladorVerNomina(empleado, empleadod, asistdao, salario, fnomina);
        jDesktopPane1.add(fnomina); //Crea un objeto de tipo form y sobrepone un panel sobre otro

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = fnomina.getSize();
        fnomina.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        fnomina.show();
    }//GEN-LAST:event_jMIGenerarNominaActionPerformed

    private void jMILiquidarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILiquidarEmpleadoActionPerformed

        FrmLiquidacion fliquidacion = new FrmLiquidacion();
        Salario salario = new Salario();
        Empleado empleado = new Empleado();
        EmpleadoDAO empleadod = new EmpleadoDAO();

        SalarioDAO saladao = new SalarioDAO();
        DecimalFormat df = new DecimalFormat("0,000");
        ArrayList datos = new ArrayList();

        String id = JOptionPane.showInputDialog("Por favor ingrese el número de documento del empleado");
        int salarioBase = 0, diasTrabajados = 0;
        java.sql.Date fechaCorte = null;

        try {
            salarioBase = empleadod.traerSalarioBase(id);
            diasTrabajados = saladao.traerDias(id);
            datos = empleadod.traerRegistros(id);
            fechaCorte = saladao.traerFechaCorte(id);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < datos.size(); i++) {
            empleado = (Empleado) datos.get(i);
        }

        fliquidacion.jTxEmpleado.setText(empleado.getNombres() + " " + empleado.getApellidos());

        String tipoID;
        if (empleado.getTipoId().equals("Cédula de Ciudadanía")) {
            tipoID = "CC";
        } else if (empleado.getTipoId().equals("Cédula de Extranjería")) {
            tipoID = "CE";
        } else {
            tipoID = empleado.getTipoId();
        }

        fliquidacion.jTxDocumento.setText(tipoID + " " + id);
        fliquidacion.jTxCargo.setText(empleado.getCargo());
        fliquidacion.jTxFechaCorte.setText(String.valueOf(fechaCorte) + " a");

        double cesantias = salario.cesantias(salarioBase, diasTrabajados);
        double prima = salario.prima(diasTrabajados, salarioBase);
        double vacaciones = salario.vacaciones(salarioBase, diasTrabajados);
        double intereses = salario.interesCesantias(salarioBase, diasTrabajados);
        double totalD = cesantias + prima + vacaciones + intereses;
        double totalP = cesantias + prima + vacaciones + intereses;

        fliquidacion.jTxSalarioBase.setText("$ " + String.valueOf(df.format(salarioBase)));
        fliquidacion.jTxPrima.setText("$ " + String.valueOf(df.format(prima)));
        fliquidacion.jTxCesantias.setText("$ " + String.valueOf(df.format(cesantias)));
        fliquidacion.jTxInteresesCesan.setText("$ " + String.valueOf(df.format(intereses)));
        fliquidacion.jTxVacaciones.setText("$ " + String.valueOf(df.format(vacaciones)));
        fliquidacion.jTxTotalDevengado.setText("$ " + String.valueOf(df.format(totalD)));
        fliquidacion.jTxNetoPagar.setText("$ " + String.valueOf(df.format(totalP)));
        fliquidacion.jTxConsumo.setText("$ 0");
        fliquidacion.jTxPrimaPagada.setText("$ 0");
        fliquidacion.jTxTotalDeducciones.setText("$ 0");

        ControladorLiquidacion control1 = new ControladorLiquidacion(fliquidacion, salario, empleado, empleadod);

        fliquidacion.setVisible(true);
    }//GEN-LAST:event_jMILiquidarEmpleadoActionPerformed

    public void cerrar() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                confirmarSalida();
            }
        });
    }

    public void confirmarSalida() {
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro de salir?", "Fin SIRH", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Gracias por utilizar el SIRH,\n Hasta pronto", "Agradecimiento", JOptionPane.INFORMATION_MESSAGE);
            AdministradorDAO admindao = new AdministradorDAO();
            admindao.cerrarCuenta();
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMIGenerarNomina;
    private javax.swing.JMenuItem jMILiquidarEmpleado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
