/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorActualizarEmpl;
import controlador.ControladorNovedades;
import controlador.ControladorTurnos;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import modelo.EmpleadoDAO;
import modelo.Novedades;
import modelo.NovedadesDAO;
import modelo.Turnos;
import modelo.TurnosDAO;

/**
 *
 * @author SALA406-27
 */
public class FrmVisualizarEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVisualizarEmpleados
     */
    public FrmVisualizarEmpleados() throws SQLException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCbTipoID = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTxID = new javax.swing.JTextField();
        jBtSalir = new javax.swing.JButton();

        jTbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTbEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTbEmpleadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTbEmpleados);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLEADOS");

        jLabel2.setText("Tipo Identificación");

        jCbTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECCIONE TIPO DE DOCUMENTO-", "Cédula de Ciudadanía", "Cédula de Extranjería", "PEP" }));

        jLabel3.setText("Número");

        jBtSalir.setBackground(new java.awt.Color(102, 102, 102));
        jBtSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtSalir.setForeground(new java.awt.Color(255, 255, 255));
        jBtSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jCbTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTxID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtSalir)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCbTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtSalir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Evento para re dirigir al usuario a la opcion que escoja al hacer click en los datos de un empleado registrado
    private void jTbEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbEmpleadosMousePressed
        int fila = this.jTbEmpleados.getSelectedRow();

        String[] botones = {"Asignar Turnos", "Actualizar Empleado", "Ingresar Novedad Empleado"};
        DefaultTableModel modelo = (DefaultTableModel) jTbEmpleados.getModel();
        String nombre = (String) modelo.getValueAt(fila, 2);
        String apellidos = (String) modelo.getValueAt(fila, 3);
        String empleado = nombre + " " + apellidos;
        String id = (String) modelo.getValueAt(fila, 1);

        int respuesta = JOptionPane.showOptionDialog(this, "¿Que acción desea realizar?", "Configuración",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botones, botones[0]);
        if (respuesta == JOptionPane.YES_OPTION) {

            FrmTurnos formT = new FrmTurnos();
            TurnosDAO turnosdao = new TurnosDAO();
            Turnos turnos = new Turnos();

            formT.jTxNombreEmpleado.setText(empleado);
            formT.jTxID.setText(id);
            ControladorTurnos control = new ControladorTurnos(formT, turnos, turnosdao);

            formT.setVisible(true);
        } else if (respuesta == JOptionPane.NO_OPTION) {

            FrmActualizarEmpl formA = new FrmActualizarEmpl();
            formA.jCbTipoID.setEnabled(false);
            formA.jTxNumeroID.setEnabled(false);

            Empleado empl = new Empleado();
            EmpleadoDAO empldao = new EmpleadoDAO();
            ArrayList<Empleado> listEmpleados = new ArrayList();

            try {
                listEmpleados = empldao.datosEmpleado(id);

                for (int j = 0; j < listEmpleados.size(); j++) {
                    for (int i = 0; i < formA.jCbTipoID.getItemCount(); i++) {
                        if (formA.jCbTipoID.getItemAt(i).equals(listEmpleados.get(j).getTipoId())) {
                            formA.jCbTipoID.setSelectedIndex(i);
                        }
                    }
                    for (int x = 0; x < formA.jCbRH.getItemCount(); x++) {
                        if (formA.jCbRH.getItemAt(x).equals(listEmpleados.get(j).getRh())) {
                            formA.jCbRH.setSelectedIndex(x);
                        }
                    }
                    formA.jTxNumeroID.setText(listEmpleados.get(j).getCedula());
                    formA.jTxNombres.setText(listEmpleados.get(j).getNombres());
                    formA.jTxApellidos.setText(listEmpleados.get(j).getApellidos());
                    formA.jDtFechaNacimiento.setDate(listEmpleados.get(j).getFechaNacimiento());
                    formA.jTxTelefono.setText(listEmpleados.get(j).getTelefono());
                    formA.jTxDireccion.setText(listEmpleados.get(j).getDireccion());
                    formA.jTxCargo.setText(listEmpleados.get(j).getCargo());
                    formA.jCbARL.setSelectedIndex(0);
                    formA.jTxEPS.setText(listEmpleados.get(j).getEps());
                    formA.jTxSalario.setText(String.valueOf(listEmpleados.get(j).getSalarioBase()));
                }

            } catch (SQLException ex) {
                Logger.getLogger(FrmVisualizarEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }

            ControladorActualizarEmpl control = new ControladorActualizarEmpl(formA, empl, empldao);
            formA.setVisible(true);
        } else if (respuesta == CANCEL_OPTION) {
            NovedadesDAO admindao = new NovedadesDAO();
            Novedades admin = new Novedades();

            FrmNovedades form1 = new FrmNovedades();
            form1.jTxNombres.setText(empleado);
            form1.jTFCedula.setText(id);
            form1.jTxNombres.setEnabled(false);
            form1.jTFCedula.setEnabled(false);
            ControladorNovedades control1 = new ControladorNovedades(form1, admin, admindao);
            form1.setVisible(true);
        }

    }//GEN-LAST:event_jTbEmpleadosMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtSalir;
    public javax.swing.JComboBox<String> jCbTipoID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTbEmpleados;
    public javax.swing.JTextField jTxID;
    // End of variables declaration//GEN-END:variables
}
