/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static jdk.nashorn.internal.objects.NativeMath.round;
import modelo.PruebaLogicaNomina;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.AsistenciaDAO;
import modelo.Empleado;
import modelo.EmpleadoDAO;

/**
 *
 * @author ISABELLA CARMONA C
 */
public class PruebaNomina extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form PruebaNomina
     */
    public PruebaNomina() {
        initComponents();

        modelo.addColumn("id");
        modelo.addColumn("dias T");
        modelo.addColumn("Salario");
        modelo.addColumn("Total D");
        modelo.addColumn("Cesantias");
        modelo.addColumn("Primas");
        modelo.addColumn("Vacaciones");
        modelo.addColumn("Intereses C");
        modelo.addColumn("Total Pagar");
        modelo.addColumn("Aux Transp");
        jTbEmpleados.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbEmpleados = new javax.swing.JTable();
        jTxDocumento = new javax.swing.JTextField();
        jBtCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jueputa vida la mia ome");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTbEmpleados);

        jBtCalcular.setText("Calcular");
        jBtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jTxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jBtCalcular)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtCalcular))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCalcularActionPerformed

        String documento = jTxDocumento.getText();

        PruebaLogicaNomina prueba = new PruebaLogicaNomina();
        EmpleadoDAO empldao = new EmpleadoDAO();
        ArrayList<String> documentos = new ArrayList();

        try {
            documentos = empldao.traerDocumentos();
        } catch (SQLException ex) {
            Logger.getLogger(PruebaNomina.class.getName()).log(Level.SEVERE, null, ex);
        }

        int salario = 0, diasTrabajados = 0;

        String[] datos = new String[10];
        String docu;
        DecimalFormat df = new DecimalFormat("0.00");
        for (int i = 0; i < documentos.size(); i++) {
            docu = documentos.get(i);

            if (docu.equals(documento)) {
                try {
                    salario = empldao.traerSalarioBase(documento);
                    diasTrabajados = prueba.diasTrabajados(documento);
                } catch (SQLException ex) {
                    Logger.getLogger(PruebaNomina.class.getName()).log(Level.SEVERE, null, ex);
                }

                double totalD = prueba.totalD(salario, diasTrabajados);
                double cesantias = prueba.cesantias(salario, diasTrabajados);
                double prima = prueba.prima(diasTrabajados, salario);
                double vacaciones = prueba.vacaciones(salario, diasTrabajados);
                double intereses = prueba.interesCesantias(salario, diasTrabajados);
                double totalP = prueba.totalPagar(salario, diasTrabajados);
                int auxTransp = prueba.auxTransp(salario);
                double auxD;

                if (auxTransp != 0) {
                    auxD = (auxTransp / 30) * diasTrabajados;
                } else {
                    auxD = 0;
                }
                datos[0] = docu;
                datos[1] = String.valueOf(diasTrabajados);
                datos[2] = String.valueOf(salario);
                datos[3] = String.valueOf(df.format(totalD));
                datos[4] = String.valueOf(df.format(cesantias));
                datos[5] = String.valueOf(df.format(prima));
                datos[6] = String.valueOf(df.format(vacaciones));
                datos[7] = String.valueOf(df.format(intereses));
                datos[8] = String.valueOf(df.format(totalP));
                datos[9] = String.valueOf(df.format(auxD));
                modelo.addRow(datos);
            }
        }
    }//GEN-LAST:event_jBtCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCalcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbEmpleados;
    private javax.swing.JTextField jTxDocumento;
    // End of variables declaration//GEN-END:variables
}
